name: Scheduled Tasks crawlOpinetData

on:
  schedule:
    - cron: '0 16,0,3,7,10 * * *' # 매일 한국 시간(KST, UTC+9) 1시, 9시, 12시, 16시, 19시에  실행
  workflow_dispatch: # 수동 실행을 위한 트리거 추가

jobs:
  get-oildata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev
          # sudo apt-get install -y chromium-browser
          # sudo apt-get install -y xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: generate .env
      #   run: |
      #     echo "REPOSITORY_TOKEN=$REPOSITORY_TOKEN" >> .env
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }  # 시크릿 사용

      - name: Run crawl_recent_oildata
        env:
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}  # GITHUB_TOKEN 추가
        run: |
          python crawl_recent_oil_data.py

      - name: Configure Git
        run: |
          git config --local user.email "yhsofa89@gmail.com"
          git config --local user.name "GitHub Actions"

      - name: Check for changes and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN 추가
        run: |
          git add json/ # 필요한 파일 추가
          if [[ $(git diff --cached --stat) ]]; then
            echo "json/ 디렉토리 내 파일 내용 변경사항 있음"
            git commit -m "Update data files from GitHub Actions" --allow-empty && git push 
          else
            echo "No changes to commit"
          fi